#!/bin/bash

#$ -M csu3@nd.edu   # Email address for job notification
#$ -m abe               # Send mail when job aborts, begins, and ends
#$ -pe smp 1            # Specify parallel environment and legal core size
#$ -q gpu               # Run on the GPU cluster
#$ -l gpu_card=1        # Run on 1 GPU card
#$ -N download          # Specify job name

module load python
source ~/llamaenv/bin/activate 

python3 hugginface.py  # the command to run your task

deactivate

